import React from "react";

function ProductsInOne() {
  const ProductsInOne = [
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-30%",
          ProductName: "Shirinlik nomi",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-40%",
          ProductName: "Shirinlik nomi 2",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-30%",
          ProductName: "Shirinlik nomi 3",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-40%",
          ProductName: "Shirinlik nomi 4",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-30%",
          ProductName: "Shirinlik nomi 5",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-40%",
          ProductName: "Shirinlik nomi 6",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-30%",
          ProductName: "Shirinlik nomi 7",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-40%",
          ProductName: "Shirinlik nomi 8",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-30%",
          ProductName: "Shirinlik nomi 9",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-40%",
          ProductName: "Shirinlik nomi 10",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-30%",
          ProductName: "Shirinlik nomi 11",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-40%",
          ProductName: "Shirinlik nomi 12",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-30%",
          ProductName: "Shirinlik nomi 13",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-40%",
          ProductName: "Shirinlik nomi 14",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-30%",
          ProductName: "Shirinlik nomi 15",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-40%",
          ProductName: "Shirinlik nomi 16",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-30%",
          ProductName: "Shirinlik nomi 17",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-40%",
          ProductName: "Shirinlik nomi 18",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-30%",
          ProductName: "Shirinlik nomi 19",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-40%",
          ProductName: "Shirinlik nomi 20",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-30%",
          ProductName: "Shirinlik nomi 21",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-40%",
          ProductName: "Shirinlik nomi 22",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-30%",
          ProductName: "Shirinlik nomi 23",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        {
          ProductImg: "https://i.ibb.co/xfNRgmQ/image-8.png",
          ProductSaleBtn: "-40%",
          ProductName: "Shirinlik nomi 24",
          ProductTitle: "///",
          ProductPrice: "Narxi sum/$",
          ProductSale: "Oldingi narxi sum/$",
        },
        // Boshqa mahsulotlar...
      ];
  return <div></div>;
}

export default ProductsInOne;
